### ISSUE TITLE
Group DM purge command fails

### ISSUE THREAD

**Issue by Khralis** [GoByeBye/DiscoRape#7]
Attempting to purge a group DM fails with the following stack-trace

```
Ignoring exception in command purge:
Traceback (most recent call last):
  File "/home/probably-a-pi/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/probably-a-pi/Desktop/SelfBots/DiscoRape/cogs/mod.py", line 123, in purge
    await ctx.purge(limit = amount+1, check = lambda m : m.pinned == False)
  File "/home/probably-a-pi/Desktop/SelfBots/DiscoRape/ext/context.py", line 31, in purge
    await self.channel.purge(*args, **kwargs)
AttributeError: 'GroupChannel' object has no attribute 'purge'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/probably-a-pi/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/probably-a-pi/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/probably-a-pi/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'GroupChannel' object has no attribute 'purge'

```

**Comment by GoByeBye** [comment]
Valid issue if I remember correctly it doesn't have error handling for system messages will be fixed in next update. In the meanwhile use clean command instead

**Comment by GoByeBye** [comment]
Fixed in [latest update](https://github.com/GoByeBye/DiscoRape/commit/724f7b622d3cecfe5799c1e6d14e09d1d6b186a1)
