### ISSUE TITLE
it says improper token has been passed.

### ISSUE THREAD

**Issue by yogesh-malware** [GoByeBye/DiscoRape#9]
[-] Loaded extension: anim
[-] Loaded extension: backup
[-] Loaded extension: crypto
[-] Loaded extension: misc
[-] Loaded extension: mod
[-] Loaded extension: memes
[-] Loaded extension: malicious
[-] Loaded extension: nsfw
[-] Loaded extension: nukes
[-] Loaded extension: noble
[-] Loaded extension: skid
[-] Loaded extension: source
[-] Loaded extension: textemotes
[-] Loaded extension: utils
Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000291EE916F70>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

D:\codes\DiscoRape-master>

**Comment by GoByeBye** [comment]
You pasted an invalid token
